# Generated by Django 3.1.1 on 2020-09-25 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('item', models.CharField(default='', max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
