# Generated by Django 3.1.1 on 2020-09-25 13:24

from django.db import migrations

ORDERS_LIST = [
    {'name': 'Person1', 'item': 'Item1', 'count': 1},
    {'name': 'Person2', 'item': 'Item2', 'count': 2},
    {'name': 'Person3', 'item': 'Item3', 'count': 3},
    {'name': 'Person4', 'item': 'Item4', 'count': 4},
    {'name': 'Person5', 'item': 'Item5', 'count': 5},
    {'name': 'Person5', 'item': 'Item5', 'count': 5},
    {'name': 'Person6', 'item': 'Item6', 'count': 6},
    {'name': 'Person7', 'item': 'Item7', 'count': 7},
    {'name': 'Person8', 'item': 'Item8', 'count': 8},
    {'name': 'Person9', 'item': 'Item9', 'count': 9},
    {'name': 'Person10', 'item': 'Item10', 'count': 10},
]


def insert_initial_data(apps, schema_editor):
    OrdersModel = apps.get_model('DemoApp', 'OrdersModel')

    orders_objects = []
    for order in ORDERS_LIST:
        orders_objects.append(OrdersModel(
            name=order['name'],
            item=order['item'],
            count=order['count']
        ))

    OrdersModel.objects.bulk_create(orders_objects)


def delete_initial_data(apps, schema_editor):
    OrdersModel = apps.get_model('DemoApp', 'OrdersModel')

    orders_objects = []
    for order in ORDERS_LIST:
        try:
            orders_objects.append(OrdersModel.objects.get(
                name=order['name'],
                item=order['item'],
                count=order['count']
            ))
        except:
            pass

    OrdersModel.objects.bulk_delete(orders_objects)


class Migration(migrations.Migration):
    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data, reverse_code=delete_initial_data),
    ]
