version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: tradebyte
      POSTGRES_USER: tradebyte

  web:
    build:
      context: .
    environment:
      ENABLE_POSTGRES: 1
      POSTGRES_DB: tradebyte
      POSTGRES_USER: tradebyte
      POSTGRES_PASSWORD: tradebyte
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    command: ["sh", "-c", "./wait-for-it.sh postgres:5432 -- echo up && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]
    depends_on:
      - postgres